var countries_taxa=[['ISO2','Country name', 'Number of taxa'],
['AW', 'Aruba', 3],
['AF', 'Afghanistan', 393],
['AO', 'Angola', 337],
['AI', 'Anguilla', 44],
['AL', 'Albania', 636],
['AD', 'Andorra', 1],
['AN', 'Netherlands Antilles', 51],
['AE', 'United Arab Emirates', 16],
['AR', 'Argentina', 348],
['AM', 'Armenia', 481],
['AG', 'Antigua and Barbuda', 126],
['AU', 'Australia', 527],
['AT', 'Austria', 561],
['AZ', 'Azerbaijan', 529],
['BI', 'Burundi', 121],
['BE', 'Belgium', 425],
['BJ', 'Benin', 205],
['BF', 'Burkina Faso', 85],
['BD', 'Bangladesh', 258],
['BG', 'Bulgaria', 674],
['BH', 'Bahrain', 15],
['BS', 'Bahamas', 122],
['BA', 'Bosnia and Herzegovina', 259],
['BY', 'Belarus', 383],
['BZ', 'Belize', 287],
['BM', 'Bermuda', 22],
['BO', 'Bolivia - Plurinational State of ', 460],
['BR', 'Brazil', 692],
['BB', 'Barbados', 98],
['BN', 'Brunei Darussalam', 54],
['BT', 'Bhutan', 405],
['BW', 'Botswana', 236],
['CF', 'Central African Republic', 187],
['CA', 'Canada', 527],
['CC', 'Cocos - Keeling Islands', 3],
['CH', 'Switzerland', 508],
['CL', 'Chile', 125],
['CN', 'China', 1947],
['CI', "'Côte d'Ivoire'", 328],
['CM', 'Cameroon', 399],
['CD', 'Democratic Republic of the Congo', 402],
['CG', 'Congo', 126],
['CK', 'Cook Islands', 10],
['CO', 'Colombia', 504],
['KM', 'Comoros', 45],
['CV', 'Cabo Verde', 44],
['CR', 'Costa Rica', 375],
['CU', 'Cuba', 258],
['CX', 'Christmas Island', 6],
['KY', 'Cayman Islands', 53],
['CY', 'Cyprus', 304],
['CZ', 'Czechia', 366],
['DE', 'Germany', 543],
['DJ', 'Djibouti', 31],
['DM', 'Dominica', 128],
['DK', 'Denmark', 366],
['DO', 'Dominican Republic', 140],
['DZ', 'Algeria', 494],
['EC', 'Ecuador', 441],
['EG', 'Egypt', 311],
['ER', 'Eritrea', 121],
['EH', 'Western Sahara', 2],
['ES', 'Spain', 791],
['EE', 'Estonia', 332],
['ET', 'Ethiopia', 356],
['FI', 'Finland', 303],
['FJ', 'Fiji', 71],
['FK', 'Falkland Islands - Malvinas', 1],
['FR', 'France', 780],
['FO', 'Faroe Islands', 22],
['FM', 'Micronesia - Federated States of', 61],
['GA', 'Gabon', 195],
['GB', 'United Kingdom of Great Britain and Northern Ireland', 415],
['GE', 'Georgia', 498],
['GH', 'Ghana', 367],
['GI', 'Gibraltar', 1],
['GN', 'Guinea', 251],
['GP', 'Guadeloupe', 175],
['GM', 'Gambia', 131],
['GW', 'Guinea-Bissau', 158],
['GQ', 'Equatorial Guinea', 122],
['GR', 'Greece', 726],
['GD', 'Grenada', 120],
['GL', 'Greenland', 41],
['GT', 'Guatemala', 435],
['GF', 'French Guiana', 256],
['GU', 'Guam', 22],
['GY', 'Guyana', 305],
['HK', 'China Hong Kong Special Administrative Region', 47],
['HN', 'Honduras', 367],
['HR', 'Croatia', 466],
['HT', 'Haiti', 114],
['HU', 'Hungary', 523],
['ID', 'Indonesia', 839],
['IN', 'India', 1304],
['IE', 'Ireland', 303],
['IR', 'Iran - Islamic Republic of', 595],
['IQ', 'Iraq', 339],
['IS', 'Iceland', 80],
['IL', 'Israel', 353],
['IT', 'Italy', 825],
['JM', 'Jamaica', 205],
['JO', 'Jordan', 237],
['JP', 'Japan', 637],
['KZ', 'Kazakhstan', 394],
['KE', 'Kenya', 429],
['KG', 'Kyrgyzstan', 328],
['KH', 'Cambodia', 362],
['KI', 'Kiribati', 4],
['KN', 'Saint Kitts and Nevis', 71],
['KR', 'Republic of Korea', 48],
['KW', 'Kuwait', 32],
['LA', "'Lao People's Democratic Republic'", 442],
['LB', 'Lebanon', 385],
['LR', 'Liberia', 206],
['LY', 'Libya', 273],
['LC', 'Saint Lucia', 127],
['LI', 'Liechtenstein', 5],
['LK', 'Sri Lanka', 481],
['LS', 'Lesotho', 70],
['LT', 'Lithuania', 356],
['LU', 'Luxembourg', 7],
['LV', 'Latvia', 334],
['MO', 'China Macao Special Administrative Region', 3],
['MA', 'Morocco', 497],
['MD', 'Republic of Moldova', 367],
['MG', 'Madagascar', 208],
['MV', 'Maldives', 7],
['MX', 'Mexico', 829],
['MH', 'Marshall Islands', 14],
['MK', 'The former Yugoslav Republic of Macedonia', 246],
['ML', 'Mali', 209],
['MT', 'Malta', 23],
['MM', 'Myanmar', 797],
['ME', 'Montenegro', 253],
['MN', 'Mongolia', 296],
['MP', 'Northern Mariana Islands', 20],
['MZ', 'Mozambique', 363],
['MR', 'Mauritania', 63],
['MS', 'Montserrat', 92],
['MQ', 'Martinique', 175],
['MU', 'Mauritius', 87],
['MW', 'Malawi', 299],
['MY', 'Malaysia', 744],
['NA','Namibia', 227],
['NC', 'New Caledonia', 57],
['NE', 'Niger', 135],
['NG', 'Nigeria', 442],
['NI', 'Nicaragua', 367],
['NU', 'Niue', 12],
['NL', 'Netherlands', 401],
['NO', 'Norway', 349],
['NP', 'Nepal', 606],
['NR', 'Nauru', 2],
['NZ', 'New Zealand', 30],
['OM', 'Oman', 90],
['PK', 'Pakistan', 567],
['PA', 'Panama', 351],
['PN', 'Pitcairn', 3],
['PE', 'Peru', 546],
['PH', 'Philippines', 532],
['PW', 'Palau', 19],
['PG', 'Papua New Guinea', 337],
['PL', 'Poland', 491],
['PR', 'Puerto Rico', 221],
['KP', "'Democratic People's Republic of Korea'", 30],
['PT', 'Portugal', 529],
['PY', 'Paraguay', 271],
['PS', 'State of Palestine', 1],
['PF', 'French Polynesia', 40],
['QA', 'Qatar', 14],
['RE', 'Réunion', 51],
['RO', 'Romania', 621],
['RU', 'Russian Federation', 694],
['RW', 'Rwanda', 146],
['SA', 'Saudi Arabia', 153],
['SD', 'Sudan', 320],
['SN', 'Senegal', 279],
['SG', 'Singapore', 58],
['SH', 'Saint Helena', 4],
['SJ', 'Svalbard and Jan Mayen Islands', 20],
['SB', 'Solomon Islands', 90],
['SL', 'Sierra Leone', 272],
['SV', 'El Salvador', 267],
['SO', 'Somalia', 198],
['PM', 'Saint Pierre and Miquelon', 17],
['RS', 'Serbia', 389],
['SS', 'South Sudan', 320],
['ST', 'Sao Tome and Principe', 40],
['SR', 'Suriname', 273],
['SK', 'Slovakia', 368],
['SI', 'Slovenia', 402],
['SE', 'Sweden', 391],
['SZ', 'Swaziland', 200],
['SC', 'Seychelles', 47],
['SY', 'Syrian Arab Republic', 408],
['TC', 'Turks and Caicos Islands', 6],
['TD', 'Chad', 126],
['TG', 'Togo', 222],
['TH', 'Thailand', 777],
['TJ', 'Tajikistan', 272],
['TM', 'Turkmenistan', 281],
['TL', 'Timor-Leste', 8],
['TO', 'Tonga', 24],
['TT', 'Trinidad and Tobago', 124],
['TN', 'Tunisia', 373],
['TR', 'Turkey', 827],
['TW', 'Tuvalu', 574],
['TZ', 'United Republic of Tanzania', 498],
['UG', 'Uganda', 404],
['UA', 'Ukraine', 642],
['UM', 'United States Minor Outlying Islands', 1],
['UY', 'Uruguay', 144],
['US', 'United States of America', 1048],
['UZ', 'Uzbekistan', 236],
['VC', 'Saint Vincent and the Grenadines', 140],
['VE', 'Venezuela - Bolivarian Republic of', 442],
['VG', 'British Virgin Islands', 61],
['VI', 'United States Virgin Islands', 76],
['VN', 'Viet Nam', 731],
['VU', 'Vanuatu', 52],
['WF', 'Wallis and Futuna Islands', 3],
['WS', 'Samoa', 33],
['YE', 'Yemen', 181],
['ZA', 'South Africa', 397],
['ZM', 'Zambia', 322],
['ZW', 'Zimbabwe', 328]
];
